feat: detect install command
jsmrcaga/action-netlify-deploy pull request #16
Opened 2021-03-17 12:56 UTC by tpluscode

2021-03-25 09:57 UTC, jsmrcaga requested changes

2021-03-25 09:57 UTC, jsmrcaga commented on entrypoint.sh
> +	yarn
I don't think we have `yarn` installed on the running docker , do we ?

2021-03-25 10:00 UTC, tpluscode commented on entrypoint.sh
> +	yarn
Sure do. GitHub installs yarn by default. Here's an [example job](https://github.com/zazuko/openlayers-elements/runs/2131379409?check_suite_focus=true#step:6:23) running from my branch

2021-03-26 11:12 UTC, jsmrcaga approved these changes

2021-03-26 11:12 UTC, merged