Install node using nvm
jsmrcaga/action-netlify-deploy pull request #23
Opened 2021-11-06 18:57 UTC by tpluscode

Node 17 broke my webpack build because of changes in OpenSSL

In this PR I added support for `.nvmrc` file so that the right node version will be installed if overridden in the repo.

2021-11-06 18:58 UTC, tpluscode commented on Dockerfile
> +FROM node:current-stretch
Less slim image which comes with `curl`

2021-11-06 18:59 UTC, tpluscode commented on entrypoint.sh
> +nvm install
I install `netlify-cli` first, because once nvm installs into `$HOME` it is no longer possible to install globally. 

Better ideas welcome

2021-11-07 09:52 UTC, jsmrcaga requested changes

2021-11-07 09:52 UTC, jsmrcaga commented on README.md
> +To select a different release, create an `.nvmrc` file with the desired version range.
Hey @tpluscode, why don't we add the node version as an input instead?

This would allow users to
- specify the node version on their workflow without creating a nvmrc file
- allow nvm users to "do nothing" since they will already have a nvmrc file
- and those who don't use nvm and don't specify a version will have the latest node version

2021-11-07 09:53 UTC, jsmrcaga commented
Also, add yourself in a Contributors section on the README! I completely forgot to ;)

2021-11-10 07:52 UTC, tpluscode commented on README.md
> +To select a different release, create an `.nvmrc` file with the desired version range.
Done 👌

2021-11-10 11:38 UTC, jsmrcaga approved these changes

2021-11-10 11:38 UTC, merged

2021-11-10 11:38 UTC, jsmrcaga commented
Thanks!!