fix: use $GITHUB_OUTPUT instead set-output(deprecated)
jsmrcaga/action-netlify-deploy pull request #37
Opened 2022-11-24 20:49 UTC by H4K1

In the deployments I noticed that some warnings were appearing due to the `set-output` being deprecated, I made the necessary changes to eliminate the warning!

I hope this is helpful, best regards

**warning image:**
![image](https://user-images.githubusercontent.com/71144997/203860782-fa713d53-b84c-47f2-b281-990cb7393be0.png)

**links**:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings

2022-11-29 07:58 UTC, jsmrcaga requested changes
Hi @H4K1 ! Thanks a lot for the Pull request, I'm guessing losing the warnings will make may devs happy ^^
I believe we could use the simpler `name=value` syntax though, what do you think?

2022-11-29 07:58 UTC, jsmrcaga commented on entrypoint.sh
> +echo "EOF" >> $GITHUB_OUTPUT
Since these are single line outputs I believe we could use the simpler one-line syntax
ex:
```yml
echo "action_state=yellow" >> $GITHUB_ENV
```

2022-11-29 16:50 UTC, H4K1 commented on entrypoint.sh
> +echo "EOF" >> $GITHUB_OUTPUT
yes @jsmrcaga, thank you for the review!
you can check again

2022-11-30 07:37 UTC, jsmrcaga approved these changes

2022-11-30 07:37 UTC, jsmrcaga commented
LGTM!
Thanks again @H4K1, I'll be releasing a new version as well!

2022-11-30 07:37 UTC, merged