feat: Switching the action from docker into composite
jsmrcaga/action-netlify-deploy pull request #42
Opened 2022-12-25 15:40 UTC by crisperit

2023-01-11 07:52 UTC, jsmrcaga requested changes
Hi @crisperit , I'm so sorry this is taking so long, I'm caught up in different projects.
Your PR looks good! I was thinking that it was not necessary to completely remove the `entrypoint.sh` file though, you could just leave it as is and call it via the composite action if I'm not mistaken. It would make for a way simpler action.yml file and much less diff in the pull request ;) 
it would also allow to make the .sh file "testable" if we ever decide/need to add unit testing

2023-01-11 07:52 UTC, jsmrcaga commented on action.yml
> +        fi
this is not necessary anymore 😉 
since we have a composite action, users are free to use actions/setup-node to setup whatever version they need, and our action should run with that version.

2023-01-12 07:18 UTC, crisperit commented on action.yml
> +        fi
Ok - removed

2023-01-12 07:18 UTC, crisperit commented
> Hi @crisperit , I'm so sorry this is taking so long, I'm caught up in different projects. Your PR looks good! I was thinking that it was not necessary to completely remove the `entrypoint.sh` file though, you could just leave it as is and call it via the composite action if I'm not mistaken. It would make for a way simpler action.yml file and much less diff in the pull request ;) it would also allow to make the .sh file "testable" if we ever decide/need to add unit testing

Done - I've returned entrypoint.sh

2023-01-17 06:41 UTC, jsmrcaga approved these changes

2023-01-17 06:42 UTC, jsmrcaga commented
@crisperit looks amazing! Sorry again for the delay!
There is some auto-formatting but since there are so many changes anyway it's ok 😉 

I'm gonna go ahead and release  a major version, thanks a lot for all the work you put in! If you'd like you can add your name to the README as well in another PR

2023-01-17 06:42 UTC, merged